"""Convert splash_animations.h to animations.js (ES module).

Reads:  D:/Project/Clawdmeter/firmware/src/splash_animations.h
Writes: D:/Project/MiniUsage/simulator/animations.js

Re-run when the source header changes.
"""

import re
from pathlib import Path

SRC = Path("D:/Project/Clawdmeter/firmware/src/splash_animations.h")
DST = Path("D:/Project/MiniUsage/simulator/animations.js")


def parse_num(s: str) -> int:
    s = s.strip()
    if s.lower().startswith("0x"):
        return int(s, 16)
    return int(s)


def main() -> None:
    src = SRC.read_text(encoding="utf-8")

    # discover animation names in the order they appear
    names = []
    seen = set()
    for m in re.finditer(r"splash_(\w+)_palette\[10\]", src):
        n = m.group(1)
        if n not in seen:
            seen.add(n)
            names.append(n)

    out = ["// Auto-generated by convert_animations.py — do not edit by hand.",
           "// Source: D:/Project/Clawdmeter/firmware/src/splash_animations.h",
           "",
           "export const ANIMATIONS = {"]

    for name in names:
        # palette: { 0xXXXX, 0xXXXX, ... }
        pal_match = re.search(
            rf"splash_{name}_palette\[10\]\s*=\s*\{{([^}}]+)\}}", src
        )
        if not pal_match:
            raise RuntimeError(f"palette not found for {name}")
        palette = [parse_num(x) for x in pal_match.group(1).split(",") if x.strip()]

        # frames: [N][400] = { {...}, {...}, ... };
        frames_match = re.search(
            rf"splash_{name}_frames\[(\d+)\]\[400\]\s*=\s*\{{(.*?)\}};",
            src,
            re.DOTALL,
        )
        if not frames_match:
            raise RuntimeError(f"frames not found for {name}")
        n_frames = int(frames_match.group(1))
        frames_body = frames_match.group(2)

        # each frame is { 0,0,0,... } — captured between { and }
        inner_iter = re.findall(r"\{([0-9,\s]+?)\}", frames_body)
        if len(inner_iter) != n_frames:
            raise RuntimeError(
                f"{name}: expected {n_frames} frames, found {len(inner_iter)}"
            )
        frames = []
        for inner in inner_iter:
            vals = [int(x.strip()) for x in inner.split(",") if x.strip() != ""]
            if len(vals) != 400:
                raise RuntimeError(
                    f"{name}: frame size {len(vals)} != 400"
                )
            frames.append(vals)

        # holds: { n, n, ... }
        holds_match = re.search(
            rf"splash_{name}_holds\[\d+\]\s*=\s*\{{([^}}]+)\}}", src
        )
        if not holds_match:
            raise RuntimeError(f"holds not found for {name}")
        holds = [parse_num(x) for x in holds_match.group(1).split(",") if x.strip()]
        if len(holds) != n_frames:
            raise RuntimeError(
                f"{name}: holds {len(holds)} != frames {n_frames}"
            )

        out.append(f"  {name}: {{")
        out.append(f"    palette: [{','.join(f'0x{p:04X}' for p in palette)}],")
        out.append(f"    frames: [")
        for f in frames:
            out.append(f"      new Uint8Array([{','.join(str(b) for b in f)}]),")
        out.append(f"    ],")
        out.append(f"    holds: [{','.join(str(h) for h in holds)}],")
        out.append(f"  }},")

    out.append("};")
    out.append("")

    DST.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {DST} ({len(names)} animations, {DST.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
